{{- if .Values.secrets.create }}
{{- if .Values.secrets.app.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-chatbot-framework.fullname" . }}-app-secret
  labels:
    {{- include "ai-chatbot-framework.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.secrets.app.keys }}
  {{ . }}: ""  # Populate from external source
  {{- end }}
{{- end }}
{{- end }}

