affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: arch
          operator: In
          values:
          - arm
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: capacity
          operator: In
          values:
          - ondemand
      weight: 60
    - preference:
        matchExpressions:
        - key: capacity
          operator: In
          values:
          - spot
      weight: 40

awsRegion: ap-south-1
cloudProvider: aws

image:
  repository: 618305041992.dkr.ecr.ap-south-1.amazonaws.com/registry.k8s.io/autoscaling/cluster-autoscaler
  tag: v1.26.2

autoDiscovery:
  clusterName: prod
  tags:
    - k8s.io/cluster-autoscaler/enabled
    - k8s.io/cluster-autoscaler/prod

replicaCount: 2

additionalLabels:
  app: cluster-autoscaler
  ftowner: devops
  arch: arm

tolerations: 
- effect: NoSchedule
  key: arch
  operator: Equal
  value: arm

rbac:
  create: true
  pspEnabled: false
  serviceAccount:
    create: false
    name: "prod-cluster-autoscaler"

resources:
  limits:
    cpu: 50m
    memory: 375Mi
  requests:
    cpu: 40m
    memory: 350Mi

extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  skip-nodes-with-local-storage: false
  expander: random
  max-node-provision-time: 6m0s